spring:
  application:
    name: collie-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: collie-auth
          uri: lb://collie-auth
          predicates:
            - Path=/auth/**

        - id: collie-account
          uri: lb://collie-account
          predicates:
            - Path=/accounts/**
        
        - id: collie-microservices
          uri: lb://collie-microservices
          predicates:
            - Path=/microservices/**

        - id: collie-company
          uri: lb://collie-company
          predicates:
            - Path=/company/**

        - id: insper
          uri: https://www.insper.edu.br
          predicates:
            - Path=/

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ '*' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      POST /company
