apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: alanmath/gateway:latest
          ports:
            - containerPort: 8080
          env:

            - name: DISCOVERY_HOST
              valueFrom:
                configMapKeyRef:
                  name: discovery-configmap
                  key: DISCOVERY_HOST

