# gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: alanmath/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        env:
        - name: eureka.client.service-url.defaultZone
          value: http://localhost:8761/eureka/ 